version: "3.8"
services:
  db:
    image: postgres:15.2-alpine
    env_file:
      - .env
    container_name: ${DB_HOSTNAME}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "8080:5432"
  app:
    build: "."
    container_name: app-auth
    restart: always
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
